### PR TITLE
Version 0.1.0

### LINKED ISSUE #38: Publish an initial release
The consensus among the team seems to be that this tool is ready for at least a soft-launch, as it's perfectly usable in its current form for at least basic use cases, and we have reached (or exceeded) feature parity with our previous solution (i.e. `cargo-generate` and `esp-template`). 

We should publish a `0.1.0` release of this tool to make installation simpler for users, and no longer require installing via git. From this point we can allow the community to evaluate it and give feedback on how it can be improved.

Prior to doing this, however, I would like to ensure that we have included all functionality which we would like to have in this release. The tool itself is in okay shape I think, so I suppose the main consideration here is the template. I believe there may still be some outstanding questions/issues here which have not been resolved, so it would be nice to identify these.

Once we are happy, I will prepare a release, publish the tool, and make an announcement on Matrix (and perhaps other communication channels as well).

cc @MabezDev @bjoernQ @SergioGasquez

### PR DESCRIPTION
**Pull request by jessebraham**
Judging from the lack of feedback in #38, I will consider this tool ready for an initial release.

I've made some minor changes here, notably:

- Enforce the use of the `stable` toolchain for development
- Add additional cargo metadata to prepare for the release
- Update dependencies
- Run `clippy` checks in CI

I had additionally tried to add a `rustfmt` check, but it complains about the missing `template_files.rs` file. We could first `cargo check` the project to generate this, but I do not consider this to be a blocking issue for the release so have just chosen to omit this check for the time being.

@bjoernQ and @SergioGasquez, I will wait to merge until you have both approved this PR, so please when you have some time verify that you are happy with the state of things here. If there are any additional changes you'd like to see made I'm happy to take care of them. Once this PR is merged I will publish the package and make an announcement on Matrix.

Closes #38

### CODE REVIEW

**Comment by jessebraham** [comment]
Well, didn't take long to find an issue 😅 That's embarrassing.

Running `cargo publish --dry-run` results in:

```
error: failed to run custom build command for `esp-generate v0.1.0 (/Users/jesse/Work/esp-generate/target/package/esp-generate-0.1.0)`

Caused by:
  process didn't exit successfully: `/Users/jesse/Work/esp-generate/target/package/esp-generate-0.1.0/target/debug/build/esp-generate-6378ee0add1c70db/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at build.rs:7:25:
  called `Result::unwrap()` on an `Err` value: Error { depth: 0, inner: Io { path: Some("template"), err: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Review by SergioGasquez — COMMENTED** [review]
Changes LGTM! Just a few thoughts that may or may not be covered in this PR:
- We should update README installations instructions, to remove the `--git`
- Shall we add a MSRV check?
Thanks!

**Comment by jessebraham** [comment]
Alright seems we're back in business, thanks for the help @SergioGasquez

**Review by bjoernQ — APPROVED** [review]
I guess we are good to go

**Review by SergioGasquez — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
